version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: better-sqlite3
    versions:
    - 7.1.2
    - 7.1.4
  - dependency-name: ytdl-core
    versions:
    - 4.4.5
  - dependency-name: sqlite
    versions:
    - 4.0.19
  - dependency-name: random-meow
    versions:
    - 3.9.0
  - dependency-name: canvas
    versions:
    - 2.6.1
